[package]
name = "zombrise_client"
version = "0.1.0"
edition = "2021"
description = "A zombie survival game built with Bevy engine."

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }


zombrise_shared = { path = "../shared", features = ["client"] }
game_audio = { path = "../game_audio" }
bevy = { version = "0.17", default-features = false, features = [
    "bevy_asset",
    "bevy_scene",
    "bevy_gltf",
    "serialize",
    "animation",
    "bevy_ui",
    "bevy_ui_render",
    "bevy_winit",
    "bevy_window",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_text",
    "bevy_sprite",
    "png",
    "jpeg",
    "tonemapping_luts",
    "default_font",
    # "x11", 
    # "wayland", 
    "bevy_state",
    "zstd_rust",
    "webgl2",
] }
bevy_core_pipeline = "0.17"
lightyear = { version = "0.25", features = [
    "interpolation",
    "prediction",
    "replication",
    "input_native",
    "udp",
    "netcode",
] }
lightyear_udp = "0.25"
# bevy_replicon = "0.36"
# bevy_replicon_renet2 = "0.11"
# renet2_netcode = "0.11"
bevy_simple_text_input = "0.12"
avian3d = "0.4"
bevy-inspector-egui = "0.35.0"
bevy_mesh = "0.17.3"
bevy_input = "0.17"
leafwing-input-manager = "0.16"
fastrand = "2.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.6"

[package.metadata.deb]
maintainer = "DjakeDjone"
copyright = "2025, DjakeDjone"
license-file = ["../LICENSE"]
extended-description = """\
A zombie survival game built with Bevy engine.
This package contains the game client."""
depends = "$auto"
section = "games"
priority = "optional"
assets = [
    [
        "../target/release/zombrise_client",
        "usr/bin/zombrise",
        "755",
    ],
    [
        "assets/",
        "usr/share/zombrise/assets/",
        "644",
    ],
]

[package.metadata.deb.variants.zombrise]
name = "zombrise"
